### ISSUE TITLE
suggestions to improve your project.

### ISSUE THREAD

**Issue by benwmx** [HENRYKC24/my-portfolio#15]
### good job 👍🏽 
your project is really good and you've done a great job, we have some suggestions though to improve it more .
### suggestions ⬆️ 
1 - the gap between the social media icons is a little bit more than it should be, it can be reduced.
2-  the headers should be bold.
3 - the buttons in the desktop version of the popup modal should be in the same line as the Figma template.
4- the background images aren't displaying.

**Comment by HENRYKC24** [comment]
This has long been resolved. Thanks:pray:
