### ISSUE TITLE
Suggested changes to description section.

### ISSUE THREAD

**Issue by demuk** [HENRYKC24/my-portfolio#32]
Hello Henry,
Your portfolio is looking great, Good work.
you have a small typo under Acknowledgments section.

> A special thanks to Microverse for inspiring this project. I am indebted to you all at Microverse
> A special thanks goes to all my peers at Microverse for being there for me.

Keep Up the good work.
Warm Regards,
Kiptoo

**Comment by HENRYKC24** [comment]
Thank you so much for the feedback @demuk. Could you, please, point out the exact location of the typo? 

I will so much appreciate it if you can elucidate. I hope to hear from you soon.

**Comment by demuk** [comment]
Hello @HENRYKC24

On your README.md file
Line 61 -> - A special thanks to Microverse for inspiring this project. I indebted to you all at Microverse
A special thanks to Microverse for inspiring this project. I am indebted to you all at Microverse
Line 62 -> A special thanks goes to all my peers at Microverse for being ther for me.
A special thanks goes to all my peers at Microverse for being there for me.

**Comment by HENRYKC24** [comment]
Thank you very much. I got it now. I will address the issue next week. I appreciate

**Comment by demuk** [comment]
Thank you

**Comment by HENRYKC24** [comment]
Done! Thanks a lot. I really appreciate your contribution. Let's hook up on WhatsApp, please.
