### ISSUE TITLE
Desktop Version Code Review

### ISSUE THREAD

**Issue by DammyShittu** [HENRYKC24/my-portfolio#4]
- Please, wrap every link (navbar and social media links) in hyperlink('a') tags. This is highly important as they need to go somewhere, either on the page or your social media pages.

- Kindly check the spaces between the articles and the images in the projects section. The second and fourth projects do not seem to have any column gap.

-Also, please adjust the spaces between the page logo and the hamburger menu on the mobile view to make the spaces around them even.

Cheers 👏

**Comment by HENRYKC24** [comment]
I am highly impressed about your review, peers. I will work on those immediately.
Thank you so much:pray:

**Comment by HENRYKC24** [comment]
Thank you, guys. This has long been resolved. I greatly appreciate:pray:
